apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo-app.fullname" . }}-secret
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
type: Opaque
data:
    {{- range $key, $value := .Values.secret }}
    {{ $key }}: {{ $value | b64enc | quote }}
    {{- end }}